### ISSUE TITLE
Add docs of how the rank is computed?

### ISSUE THREAD

**Issue by maelle** [lindbrook/packageRank#1]
Nice package, I'm wondering whether you could add docs of how the rank is computed to provide users with more context?

**Comment by lindbrook** [comment]
I've fleshed out the documentation in the README. If you have the time, let me know what you think. 

I'm using the README rather than a vignette for now because CRAN reports a "C stack usage" error when rebuilding the vignette; I replicated this with rhub::check_on_debian(). This may be related to the use of memoization or it may be a platform configuration issue (there's no problem on other platforms including Ubuntu and Fedora).

**Comment by maelle** [comment]
Nice work! The README doesn't state yet how the percentiles are computed, or did I miss that?

**Comment by lindbrook** [comment]
I mistakenly thought a descriptive definition was enough. Since a more explicit example can't hurt, I've added a snippet of how the percentiles are computed.
