### ISSUE TITLE
Default date= in packageRank() and possibly elsewhere reliably fails in some time zones.

### ISSUE THREAD

**Issue by krivit** [lindbrook/packageRank#145]
For example, running the function with default arguments in Sydney causes an error:
``` r
packageRank::packageRank()
#> Error in fetchCranLog(date = ymd, memoization = memoization): Log for 2020-12-24 not (yet) available. Check your internet connection or try the previous day.
```
<sup>Created on 2020-12-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I believe this is because it's already the 25th in Australia but still the 24th on the CRAN mirror being queried.

**Comment by lindbrook** [comment]
Yes. For the most recent log, the problem is two-fold. First, the warning should explicitly state that logs are typically posted at 17:00 UTC. Second, the code relies on (your computer's) local time for the date. My working solution, [logDate()](https://github.com/lindbrook/packageRank/blob/utc/R/logDate.R), computes warnings and the date of available logs using the more granular UTC date/time.

**Comment by lindbrook** [comment]
version >= 0.3.5.9123 should fix this.
